#include "gtest/gtest.h"
#include <nlohmann/json.hpp>

using namespace nlohmann;

#include <entities/AppStreamMetadataExtractor.h>

TEST(NLOHMANN_JSON, comparison) {
    json j = json::object();
    j["answer"]["everything"] = 42;
    j.dump();
    ASSERT_EQ(j.dump(), "{\"answer\":{\"everything\":42}}");  // true

}

TEST(AppStreamMetadataExtractorTest, getContent) {
    AppStreamMetadataExtractor extractor(TEST_DATA_DIR"/appimagetool.appdata.xml");
    json expected = R"({"description":"\n    <p>\n      appimagetool is a tool that lets you generate AppImage files. An AppImage\n      is a self-running bundle that contains an application and everything\n      it needs to run that cannot reasonably expected to be part of each target system.\n    </p>\n    <p>\n      This can include libraries that are not commonly available on target systems,\n      resources such as translations, icons, fonts, and other auxiliary files.\n      appimagetool makes it easy to take an AppDir (e.g., generated by linuxdeployqt)\n      and turn it into an AppImage.\n    </p>\n    <p>\n      You can also embed update information so that your users can update the AppImage\n      using binary delta updates with the AppImageUpdate tool.\n      You can also sign the AppImage with GPG.\n    </p>\n  ","id":"appimagetool.desktop","metadata_license":"MIT","name":"appimagetool","project_group":"AppImage","project_license":"MIT","summary":"Create AppImage files","urls":{"homepage":"https://github.com/probonopd/appimagetool"}})"_json;

    auto result = extractor.getContent();
    ASSERT_EQ(result.dump(), expected.dump());
}


int main(int argc, char **argv) {
    ::testing::InitGoogleTest(&argc, argv);
    return RUN_ALL_TESTS();
}