#include "gtest/gtest.h"
#include <nlohmann/json.hpp>

using namespace nlohmann;

#include <entities/FileMetadataExtractor.h>

TEST(FieleMetadataExtractorTest, getContent) {
    FileMetadataExtractor extractor(TEST_DATA_DIR"/appimagetool-x86_64.AppImage");
    json expected = R"({"abstract":{"default":"Tool to generate AppImages from AppDirs"},"categories":["Development"],"description":{"default":"\n    <p>\n      appimagetool is a tool that lets you generate AppImage files. An AppImage\n      is a self-running bundle that contains an application and everything\n      it needs to run that cannot reasonably expected to be part of each target system.\n    </p>\n    <p>\n      This can include libraries that are not commonly available on target systems,\n      resources such as translations, icons, fonts, and other auxiliary files.\n      appimagetool makes it easy to take an AppDir (e.g., generated by linuxdeployqt)\n      and turn it into an AppImage.\n    </p>\n    <p>\n      You can also embed update information so that your users can update the AppImage\n      using binary delta updates with the AppImageUpdate tool.\n      You can also sign the AppImage with GPG.\n    </p>\n  "},"file":{"architecture":"i386","sha512checksum":"8502bd1a35d95f083775404c744cc9cb1efd1c4521be437598044534a664903577693396ee07e6291dc77e9bed1d033df3c0351a1a33d3ed3bc9e3b868093331","size":1882040,"type":2},"format":1,"icon":"","id":"appimagetool.desktop","license":{"id":"MIT"},"links":{"homepage":"https://github.com/probonopd/appimagetool"},"name":{"default":"appimagetool"}})"_json;

    auto result = extractor.extractMetadata();
    ASSERT_EQ(result.dump(), expected.dump());
}


int main(int argc, char **argv) {
    ::testing::InitGoogleTest(&argc, argv);
    return RUN_ALL_TESTS();
}